import { useMemo } from 'react'
import { useNavigate } from 'react-router-dom'
import { Header } from '../components/common/Header'
import { Badge } from '../components/ui/Badge'
import { Button } from '../components/ui/Button'
import { useProperties } from '../context/PropertiesContext'
import { useAgreements } from '../context/AgreementsContext'
import { useAuth } from '../context/AuthContext'
import { formatCurrency } from '../utils/currency'
import { agreementStatusVariant } from '../utils/agreementStatus'

function formatDate(iso: string): string {
  const date = new Date(`${iso}T00:00:00`)
  if (Number.isNaN(date.getTime())) return iso
  return date.toLocaleDateString('en-IN', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  })
}

const AgreementsPage = () => {
  const navigate = useNavigate()
  const { getPropertyById } = useProperties()
  const { agreements, loading, error } = useAgreements()
  const { user, role, isAuthenticated } = useAuth()

  const visible = useMemo(() => {
    if (!isAuthenticated || !user) return agreements
    if (role === 'admin') return agreements
    if (role === 'owner') {
      return agreements.filter((agreement) => agreement.ownerId === user.id)
    }
    return agreements.filter(
      (agreement) =>
        agreement.tenantId === user.id || agreement.tenantName === user.name,
    )
  }, [agreements, isAuthenticated, role, user])

  return (
    <div className="flex min-h-screen flex-col bg-rentify-whiteOff">
      <Header />

      <main className="mx-auto w-full max-w-6xl flex-1 px-4 pb-16 pt-8 sm:px-6">
        <div className="flex flex-wrap items-end justify-between gap-3">
          <div>
            <h1 className="font-display text-2xl font-bold tracking-tight text-rentify-navy sm:text-3xl">
              Rent Agreements
            </h1>
            <p className="mt-2 text-rentify-grayMuted">
              {visible.length === 0
                ? 'No agreements yet'
                : `${visible.length} ${visible.length === 1 ? 'agreement' : 'agreements'}`}{' '}
              · Information, documents, signatures, lawyer review, final legal
              agreement, completed and rejected.
            </p>
          </div>
          <Button onClick={() => navigate('/search')}>Start from a property</Button>
        </div>

        <div className="mt-4 rounded-xl border border-rentify-purpleLight bg-rentify-purpleLight3 px-4 py-3 text-sm text-rentify-grayMuted">
          Rentify prepares the agreement <strong>package for lawyer review</strong>.
          The final legal rent agreement is prepared and issued by a lawyer — not
          generated by Rentify.
        </div>

        {!isAuthenticated ? (
          <div className="mt-7 rounded-2xl border border-rentify-grayLight bg-white px-6 py-12 text-center shadow-sm">
            <h2 className="font-display text-lg font-semibold text-rentify-navy">
              Sign in to view agreements
            </h2>
            <p className="mx-auto mt-2 max-w-md text-sm text-rentify-grayMuted">
              Agreements are linked to your account and role.
            </p>
            <div className="mt-6 flex justify-center">
              <Button onClick={() => navigate('/auth')}>Sign In</Button>
            </div>
          </div>
        ) : loading && agreements.length === 0 ? (
          <div
            className="mt-7 rounded-2xl border border-rentify-grayLight bg-white px-6 py-12 text-center shadow-sm text-rentify-grayMuted"
            role="status"
            aria-live="polite"
          >
            Loading agreements…
          </div>
        ) : error ? (
          <div
            className="mt-7 rounded-2xl border border-rentify-cautionOrange/50 bg-rentify-purpleLight3 px-6 py-10 text-center text-sm text-rentify-navy"
            role="alert"
          >
            {error}
          </div>
        ) : visible.length > 0 ? (
          <div className="mt-7 overflow-hidden rounded-2xl border border-rentify-grayLight bg-white shadow-sm">
            <div className="overflow-x-auto">
              <table className="w-full min-w-[760px] text-left text-sm">
                <thead>
                  <tr className="border-b border-rentify-grayLight bg-rentify-whiteOff text-xs font-semibold uppercase tracking-wider text-rentify-grayMuted">
                    <th scope="col" className="px-4 py-3">
                      Property
                    </th>
                    <th scope="col" className="px-4 py-3">
                      Tenant
                    </th>
                    <th scope="col" className="px-4 py-3">
                      Owner
                    </th>
                    <th scope="col" className="px-4 py-3">
                      Rent
                    </th>
                    <th scope="col" className="px-4 py-3">
                      Term
                    </th>
                    <th scope="col" className="px-4 py-3">
                      Status
                    </th>
                    <th scope="col" className="px-4 py-3">
                      <span className="sr-only">Actions</span>
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {visible.map((agreement) => {
                    const property = getPropertyById(agreement.propertyId)
                    return (
                      <tr
                        key={agreement.id}
                        className="border-b border-rentify-grayLight transition-colors last:border-0 hover:bg-rentify-purpleLight3"
                      >
                        <td className="px-4 py-3">
                          <span className="font-medium text-rentify-navy">
                            {property?.title ?? agreement.propertyTitle ?? 'Property unavailable'}
                          </span>
                          <span className="block text-xs text-rentify-grayMuted">
                            {property?.location ?? 'Vadodara'}, Vadodara
                          </span>
                        </td>
                        <td className="px-4 py-3 text-rentify-grayMuted">
                          {agreement.tenantName}
                        </td>
                        <td className="px-4 py-3 text-rentify-grayMuted">
                          {agreement.ownerName}
                        </td>
                        <td className="px-4 py-3 font-medium text-rentify-navy">
                          {formatCurrency(agreement.monthlyRent)}/month
                        </td>
                        <td className="px-4 py-3 text-rentify-grayMuted">
                          {formatDate(agreement.startDate)} →{' '}
                          {formatDate(agreement.endDate)}
                        </td>
                        <td className="px-4 py-3">
                          <Badge variant={agreementStatusVariant(agreement.status)}>
                            {agreement.status}
                          </Badge>
                        </td>
                        <td className="px-4 py-3 text-right">
                          <button
                            type="button"
                            onClick={() => navigate(`/agreements/${agreement.id}`)}
                            className="font-semibold text-rentify-navy transition-colors hover:text-rentify-lightNavy focus-visible:outline-none focus-visible:underline"
                          >
                            View
                          </button>
                        </td>
                      </tr>
                    )
                  })}
                </tbody>
              </table>
            </div>
          </div>
        ) : (
          <div className="mt-7 rounded-2xl border border-rentify-grayLight bg-white px-6 py-14 text-center shadow-sm">
            <h2 className="font-display text-lg font-semibold text-rentify-navy">
              No agreements yet
            </h2>
            <p className="mx-auto mt-2 max-w-md text-sm text-rentify-grayMuted">
              Open a property and choose “Start Rent Agreement” to collect
              information, documents and signatures, then send the package for
              lawyer review.
            </p>
            <div className="mt-6 flex justify-center">
              <Button onClick={() => navigate('/search')}>
                Browse properties
              </Button>
            </div>
          </div>
        )}
      </main>
    </div>
  )
}

export default AgreementsPage
